import { PregnancyWeek } from '../types/pregnancy';

export const PREGNANCY_WEEKS: PregnancyWeek[] = [
  {
    week: 4,
    trimester: 1,
    babySize: 'Poppy seed',
    babyWeight: '<1g',
    babyDevelopment: 'The embryo implants in the uterus. The neural tube, which becomes the brain and spinal cord, begins forming. The heart starts to develop.',
    maternalChanges: 'You may miss your period. Some women experience light spotting (implantation bleeding), fatigue, and breast tenderness.',
    tips: ['Start taking prenatal vitamins with folic acid', 'Schedule your first prenatal appointment', 'Avoid alcohol, smoking, and raw fish'],
  },
  {
    week: 5,
    trimester: 1,
    babySize: 'Sesame seed',
    babyWeight: '<1g',
    babyDevelopment: 'The heart begins beating. Arm and leg buds start forming. The neural tube continues developing into the brain and spinal cord.',
    maternalChanges: 'Morning sickness may begin. Increased urination, fatigue, and mood swings are common.',
    tips: ['Eat small, frequent meals to manage nausea', 'Stay hydrated', 'Get plenty of rest'],
  },
  {
    week: 6,
    trimester: 1,
    babySize: 'Lentil',
    babyWeight: '<1g',
    babyDevelopment: 'Facial features begin forming — nose, mouth, ears. The heart beats about 150 times per minute. Tiny fingers and toes start to develop.',
    maternalChanges: 'Nausea and vomiting may intensify. Breast tenderness continues. You may feel more tired than usual.',
    tips: ['Ginger tea can help with nausea', 'Consider wearing a sea-band for motion sickness', 'Avoid strong smells if they trigger nausea'],
  },
  {
    week: 7,
    trimester: 1,
    babySize: 'Blueberry',
    babyWeight: '<1g',
    babyDevelopment: 'The brain is growing rapidly. Arms and legs are lengthening. The liver starts producing red blood cells.',
    maternalChanges: 'Morning sickness may peak. Food aversions and cravings may develop. Skin changes possible.',
    tips: ['Eat what you can keep down — nutrition flexibility is okay', 'Talk to your doctor about severe nausea', 'Start a pregnancy journal'],
  },
  {
    week: 8,
    trimester: 1,
    babySize: 'Raspberry',
    babyWeight: '1g',
    babyDevelopment: 'All major organs have begun forming. Fingers and toes are webbed but distinct. Baby starts making spontaneous movements.',
    maternalChanges: 'Uterus is growing. You may notice your waistband getting tighter. Fatigue and nausea continue.',
    tips: ['Your first ultrasound may be scheduled soon', 'Begin thinking about prenatal testing options', 'Maintain regular sleep schedule'],
  },
  {
    week: 9,
    trimester: 1,
    babySize: 'Cherry',
    babyWeight: '2g',
    babyDevelopment: 'Baby is now officially a fetus. Tiny muscles form, allowing for movement. External ears are forming.',
    maternalChanges: 'Mood swings may increase due to hormonal changes. Some women notice thicker, shinier hair.',
    tips: ['Continue prenatal vitamins', 'Gentle exercise like walking is beneficial', 'Discuss genetic testing with your provider'],
  },
  {
    week: 10,
    trimester: 1,
    babySize: 'Strawberry',
    babyWeight: '4g',
    babyDevelopment: 'All vital organs are formed and starting to function. Tiny tooth buds appear. Fingers and toes are no longer webbed.',
    maternalChanges: 'Visible veins may appear on breasts and abdomen. Round ligament pain may begin.',
    tips: ['Stay active with gentle exercise', 'Eat iron-rich foods to prevent anemia', 'Start planning your prenatal care schedule'],
  },
  {
    week: 11,
    trimester: 1,
    babySize: 'Fig',
    babyWeight: '7g',
    babyDevelopment: 'Baby can open and close fists. Tooth buds continue developing. Bones are starting to harden.',
    maternalChanges: 'Morning sickness may start to ease. Energy levels may begin to improve.',
    tips: ['Consider a maternity support belt if needed', 'Start doing Kegel exercises', 'Plan for the first trimester screening'],
  },
  {
    week: 12,
    trimester: 1,
    babySize: 'Lime',
    babyWeight: '14g',
    babyDevelopment: 'Reflexes are developing — baby can curl toes and make sucking movements. Kidneys begin producing urine. Fingernails form.',
    maternalChanges: 'End of first trimester! Nausea often eases. You may start to show. The uterus moves up above the pelvic bone.',
    tips: ['Celebrate reaching the end of the first trimester!', 'Share the news if you haven\'t already', 'Schedule second trimester appointments'],
  },
  {
    week: 13,
    trimester: 1,
    babySize: 'Peach',
    babyWeight: '23g',
    babyDevelopment: 'Vocal cords are forming. Intestines move from the umbilical cord into the abdomen. Fingerprints are forming.',
    maternalChanges: 'Energy levels may increase. Appetite may return. You may notice less nausea.',
    tips: ['Start planning maternity wardrobe', 'Continue regular exercise', 'Consider enrolling in prenatal classes'],
  },
  {
    week: 14,
    trimester: 2,
    babySize: 'Lemon',
    babyWeight: '43g',
    babyDevelopment: 'Baby can squint, frown, and grimace. The roof of the mouth is formed. Baby may start sucking thumb.',
    maternalChanges: 'Welcome to the second trimester! Many women feel a surge of energy. Appetite usually increases.',
    tips: ['Enjoy the "honeymoon trimester"', 'Plan a babymoon if desired', 'Start sleeping on your side'],
  },
  {
    week: 16,
    trimester: 2,
    babySize: 'Avocado',
    babyWeight: '100g',
    babyDevelopment: 'Baby can make facial expressions. Eyes are moving. Bones are getting stronger. Circulatory and urinary systems are functioning.',
    maternalChanges: 'You may feel the first flutters of movement (quickening). Growing belly becomes more visible.',
    tips: ['Pay attention for first movements', 'Continue prenatal vitamins', 'Stay hydrated — aim for 8-10 glasses daily'],
  },
  {
    week: 18,
    trimester: 2,
    babySize: 'Sweet potato',
    babyWeight: '190g',
    babyDevelopment: 'Baby can hear sounds! Myelin coats nerves. If female, the uterus and fallopian tubes are formed.',
    maternalChanges: 'Baby movements become more noticeable. You may experience backaches and leg cramps.',
    tips: ['Talk and sing to your baby', 'The anatomy scan ultrasound is usually around 18-20 weeks', 'Stretch before bed to prevent leg cramps'],
  },
  {
    week: 20,
    trimester: 2,
    babySize: 'Banana',
    babyWeight: '300g',
    babyDevelopment: 'Halfway there! Baby is covered in vernix caseosa (waxy coating). Taste buds are forming. Baby is very active.',
    maternalChanges: 'Belly button may start to pop out. Stretch marks may appear. Anatomy scan usually happens now.',
    tips: ['Moisturize your belly to help with itching', 'Consider a prenatal massage', 'Start thinking about the nursery'],
  },
  {
    week: 22,
    trimester: 2,
    babySize: 'Papaya',
    babyWeight: '430g',
    babyDevelopment: 'Baby looks like a miniature newborn. Eyebrows and eyelids are formed. Grip is getting stronger.',
    maternalChanges: 'Braxton Hicks contractions may begin. Swelling in hands and feet may occur.',
    tips: ['Elevate feet when possible', 'Wear comfortable, supportive shoes', 'Monitor swelling — sudden swelling needs medical attention'],
  },
  {
    week: 24,
    trimester: 2,
    babySize: 'Corn on the cob',
    babyWeight: '600g',
    babyDevelopment: 'Lungs are developing branches and surfactant. Baby responds to sound. Skin is still translucent.',
    maternalChanges: 'Glucose tolerance test is usually done around now. You may experience heartburn and indigestion.',
    tips: ['Prepare for the glucose screening test', 'Eat smaller, more frequent meals for heartburn', 'Begin researching childbirth classes'],
  },
  {
    week: 26,
    trimester: 2,
    babySize: 'Lettuce head',
    babyWeight: '760g',
    babyDevelopment: 'Eyes begin to open. Baby can respond to light. Lungs continue maturing. Brain wave activity increases.',
    maternalChanges: 'Trouble sleeping may increase. Back pain may worsen. You may notice more Braxton Hicks.',
    tips: ['Use pillows for sleep support', 'Practice relaxation techniques', 'Consider a birth plan'],
  },
  {
    week: 28,
    trimester: 3,
    babySize: 'Eggplant',
    babyWeight: '1kg',
    babyDevelopment: 'Third trimester begins! Baby can blink, dream (REM sleep), and regulate body temperature. Fat layers are building.',
    maternalChanges: 'Prenatal visits increase to every 2 weeks. Shortness of breath may occur as uterus pushes up.',
    tips: ['Start kick counting daily', 'Pack your hospital bag', 'Tour the birthing facility'],
  },
  {
    week: 30,
    trimester: 3,
    babySize: 'Cabbage',
    babyWeight: '1.3kg',
    babyDevelopment: 'Baby\'s bone marrow takes over red blood cell production. Brain is growing rapidly. Baby practices breathing.',
    maternalChanges: 'Frequent urination returns. Heartburn may worsen. Trouble finding comfortable sleep positions.',
    tips: ['Continue kick counts', 'Finalize birth plan', 'Pre-register at your hospital'],
  },
  {
    week: 32,
    trimester: 3,
    babySize: 'Squash',
    babyWeight: '1.7kg',
    babyDevelopment: 'Toenails and fingernails are fully formed. Baby practices breathing. Bones are hardening but skull remains soft.',
    maternalChanges: 'Belly button is likely fully out. Braxton Hicks may increase. Fatigue returns.',
    tips: ['Install the car seat', 'Prepare freezer meals', 'Wash and organize baby clothes'],
  },
  {
    week: 34,
    trimester: 3,
    babySize: 'Pineapple',
    babyWeight: '2.1kg',
    babyDevelopment: 'Central nervous system is maturing. Lungs are nearly fully developed. Baby is gaining weight rapidly.',
    maternalChanges: 'Pressure on bladder increases. Pelvic pain may occur. Nesting instinct may kick in.',
    tips: ['Finalize your hospital bag', 'Know the signs of preterm labor', 'Rest when you can'],
  },
  {
    week: 36,
    trimester: 3,
    babySize: 'Honeydew melon',
    babyWeight: '2.6kg',
    babyDevelopment: 'Baby is gaining about 30g per day. Skin is smooth and soft. Baby may drop into the pelvis (lightening).',
    maternalChanges: 'Breathing may ease if baby drops. Pelvic pressure increases. Weekly prenatal visits begin.',
    tips: ['Know the signs of labor', 'Review your birth plan with your provider', 'Stay close to your hospital'],
  },
  {
    week: 37,
    trimester: 3,
    babySize: 'Swiss chard bunch',
    babyWeight: '2.9kg',
    babyDevelopment: 'Baby is now "early term." Lungs are mature. Baby continues gaining fat for temperature regulation.',
    maternalChanges: 'Cervix may begin to dilate and efface. Mucus plug may pass. Increased vaginal discharge.',
    tips: ['Rest and conserve energy', 'Keep your phone charged', 'Have your support team on standby'],
  },
  {
    week: 38,
    trimester: 3,
    babySize: 'Leek',
    babyWeight: '3.1kg',
    babyDevelopment: 'Baby\'s organs are fully mature. Meconium (first stool) accumulates. Baby is in final position for birth.',
    maternalChanges: 'Nesting urges may intensify. Braxton Hicks may be more frequent. Anxiety and excitement build.',
    tips: ['Practice breathing and relaxation techniques', 'Stay active with gentle walks', 'Trust your body'],
  },
  {
    week: 39,
    trimester: 3,
    babySize: 'Watermelon',
    babyWeight: '3.3kg',
    babyDevelopment: 'Baby is full term! Brain and lungs continue to mature. Baby\'s chest is more prominent as fat stores increase.',
    maternalChanges: 'Cervix continues to prepare. You may lose your mucus plug. Contractions may start.',
    tips: ['Stay calm and patient', 'Time any contractions', 'Call your provider when contractions are 5-1-1'],
  },
  {
    week: 40,
    trimester: 3,
    babySize: 'Small pumpkin',
    babyWeight: '3.4kg',
    babyDevelopment: 'Your due date! Baby is fully developed and ready for the outside world. Average baby is about 50cm long.',
    maternalChanges: 'Labor could begin at any time. Some babies arrive after the due date — that\'s normal too.',
    tips: ['Stay patient — only 5% of babies arrive on their due date', 'Continue monitoring baby movements', 'Discuss induction options if needed'],
  },
];

export const VACCINATION_SCHEDULE_AU = [
  { age: 'Birth', vaccines: ['Hepatitis B'] },
  { age: '2 months', vaccines: ['DTPa', 'Hepatitis B', 'Polio', 'Hib', 'Pneumococcal', 'Rotavirus'] },
  { age: '4 months', vaccines: ['DTPa', 'Hepatitis B', 'Polio', 'Hib', 'Pneumococcal', 'Rotavirus'] },
  { age: '6 months', vaccines: ['DTPa', 'Hepatitis B', 'Polio', 'Hib', 'Pneumococcal'] },
  { age: '12 months', vaccines: ['MMR', 'Meningococcal ACWY', 'Pneumococcal'] },
  { age: '18 months', vaccines: ['DTPa', 'Hib', 'MMR', 'Varicella'] },
  { age: '4 years', vaccines: ['DTPa', 'Polio'] },
];

export const getBabyWeekInfo = (week: number): PregnancyWeek | null => {
  const exact = PREGNANCY_WEEKS.find(w => w.week === week);
  if (exact) return exact;

  const sorted = [...PREGNANCY_WEEKS].sort((a, b) => a.week - b.week);
  for (let i = sorted.length - 1; i >= 0; i--) {
    if (sorted[i].week <= week) return sorted[i];
  }
  return sorted[0] || null;
};
