import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, Pressable } from 'react-native';
import { Info, X, AlertTriangle, Shield } from 'lucide-react-native';
import Colors from '../constants/colors';

export const MASTER_DISCLAIMER = "F365 provides wellness insights based on patterns in your self-reported data. These insights are not medical advice, diagnosis, or treatment. Predictions reflect trends, not certainties.";

export const DISCLAIMERS = {
  prediction: "Predictions are based on recent patterns in your data and may change as we learn more.",
  aiExplanation: "This explanation is informational and not a medical diagnosis.",
  correlation: "Charts show correlations, not cause-and-effect relationships.",
  export: "Generated by F365 using user-reported data. Not intended for clinical decision-making.",
  crisis: "If you're feeling unsafe, please contact local emergency services.",
  consent: "I understand that F365 provides wellness insights, not medical advice.",
};

type DisclaimerBannerProps = {
  type: 'info' | 'warning' | 'correlation';
  message: string;
  dismissible?: boolean;
  onDismiss?: () => void;
  style?: any;
};

export const DisclaimerBanner: React.FC<DisclaimerBannerProps> = ({
  type,
  message,
  dismissible = false,
  onDismiss,
  style,
}) => {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  const handleDismiss = () => {
    setDismissed(true);
    onDismiss?.();
  };

  const getIcon = () => {
    switch (type) {
      case 'warning':
        return <AlertTriangle size={16} color={Colors.warning} />;
      case 'correlation':
        return <Info size={16} color={Colors.accent} />;
      default:
        return <Info size={16} color={Colors.primary} />;
    }
  };

  const getBorderColor = () => {
    switch (type) {
      case 'warning':
        return Colors.warning + '40';
      case 'correlation':
        return Colors.accent + '40';
      default:
        return Colors.primary + '40';
    }
  };

  const getBackgroundColor = () => {
    switch (type) {
      case 'warning':
        return Colors.warning + '10';
      case 'correlation':
        return Colors.accent + '10';
      default:
        return Colors.primary + '10';
    }
  };

  return (
    <View style={[styles.banner, { borderColor: getBorderColor(), backgroundColor: getBackgroundColor() }, style]}>
      <View style={styles.bannerContent}>
        {getIcon()}
        <Text style={styles.bannerText}>{message}</Text>
      </View>
      {dismissible && (
        <TouchableOpacity onPress={handleDismiss} style={styles.dismissButton}>
          <X size={16} color={Colors.textMuted} />
        </TouchableOpacity>
      )}
    </View>
  );
};

type PredictionDisclaimerProps = {
  style?: any;
};

export const PredictionDisclaimer: React.FC<PredictionDisclaimerProps> = ({ style }) => {
  const [modalVisible, setModalVisible] = useState(false);

  return (
    <>
      <TouchableOpacity 
        style={[styles.inlineDisclaimer, style]}
        onPress={() => setModalVisible(true)}
        activeOpacity={0.7}
      >
        <Info size={14} color={Colors.textMuted} />
        <Text style={styles.inlineDisclaimerText}>How predictions work</Text>
      </TouchableOpacity>

      <Modal
        visible={modalVisible}
        transparent
        animationType="fade"
        onRequestClose={() => setModalVisible(false)}
      >
        <Pressable style={styles.modalOverlay} onPress={() => setModalVisible(false)}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Shield size={24} color={Colors.primary} />
              <Text style={styles.modalTitle}>About Predictions</Text>
            </View>
            <Text style={styles.modalText}>{DISCLAIMERS.prediction}</Text>
            <Text style={styles.modalSubtext}>
              The more data you log, the better our predictions become. Your patterns are unique to you.
            </Text>
            <TouchableOpacity 
              style={styles.modalButton}
              onPress={() => setModalVisible(false)}
            >
              <Text style={styles.modalButtonText}>Got it</Text>
            </TouchableOpacity>
          </View>
        </Pressable>
      </Modal>
    </>
  );
};

type AIExplanationFooterProps = {
  style?: any;
};

export const AIExplanationFooter: React.FC<AIExplanationFooterProps> = ({ style }) => {
  return (
    <View style={[styles.explanationFooter, style]}>
      <Info size={12} color={Colors.textMuted} />
      <Text style={styles.explanationFooterText}>{DISCLAIMERS.aiExplanation}</Text>
    </View>
  );
};

type ExportDisclaimerFooterProps = {
  style?: any;
};

export const ExportDisclaimerFooter: React.FC<ExportDisclaimerFooterProps> = ({ style }) => {
  return (
    <View style={[styles.exportFooter, style]}>
      <AlertTriangle size={14} color={Colors.textMuted} />
      <Text style={styles.exportFooterText}>{DISCLAIMERS.export}</Text>
    </View>
  );
};

type ConsentCheckboxProps = {
  checked: boolean;
  onToggle: () => void;
  style?: any;
};

export const ConsentCheckbox: React.FC<ConsentCheckboxProps> = ({ checked, onToggle, style }) => {
  return (
    <TouchableOpacity 
      style={[styles.consentContainer, style]}
      onPress={onToggle}
      activeOpacity={0.7}
    >
      <View style={[styles.checkbox, checked && styles.checkboxChecked]}>
        {checked && <Text style={styles.checkmark}>✓</Text>}
      </View>
      <View style={styles.consentTextContainer}>
        <Text style={styles.consentText}>{DISCLAIMERS.consent}</Text>
        <Text style={styles.consentRequired}>Required to continue</Text>
      </View>
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  banner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    marginBottom: 16,
  },
  bannerContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  bannerText: {
    flex: 1,
    fontSize: 13,
    color: Colors.text,
    lineHeight: 18,
  },
  dismissButton: {
    padding: 4,
    marginLeft: 8,
  },
  inlineDisclaimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  inlineDisclaimerText: {
    fontSize: 13,
    color: Colors.text,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: Colors.background,
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 340,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.text,
  },
  modalText: {
    fontSize: 15,
    color: Colors.text,
    lineHeight: 22,
    marginBottom: 12,
  },
  modalSubtext: {
    fontSize: 13,
    color: Colors.textMuted,
    lineHeight: 18,
    marginBottom: 20,
  },
  modalButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.white,
  },
  explanationFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: Colors.muted,
    borderRadius: 6,
    marginTop: 12,
  },
  explanationFooterText: {
    flex: 1,
    fontSize: 12,
    color: Colors.text,
    lineHeight: 17,
  },
  exportFooter: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    backgroundColor: Colors.muted,
    borderRadius: 10,
    marginTop: 16,
  },
  exportFooterText: {
    flex: 1,
    fontSize: 13,
    color: Colors.text,
    lineHeight: 19,
  },
  consentContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 16,
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  checkmark: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  consentTextContainer: {
    flex: 1,
  },
  consentText: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
    fontWeight: '500',
  },
  consentRequired: {
    fontSize: 12,
    color: Colors.subtext,
    marginTop: 4,
  },
});
