-- F365 Clinic Finder - Seed Data
-- 10 AU + 10 IN + 10 PK + 10 Mock/Generic clinics

-- AUSTRALIA (10 clinics)
INSERT INTO clinics (name, country, city, state, latitude, longitude, services, wait_time, gp_referral_required, telehealth_available, packages_available, direct_booking, medicare_accepted, description, phone, website, operating_hours, accreditation) VALUES
('Monash IVF', 'AU', 'Melbourne', 'VIC', -37.8136, 144.9631, ARRAY['IVF', 'ICSI', 'Fertility Preservation', 'Egg Freezing', 'PGT'], '2-4 weeks', true, true, false, false, true, 'Leading fertility clinic with over 45 years of pioneering IVF research and treatment.', '+61 3 9420 0000', 'https://monashivf.com', 'Mon-Fri 7:30am-5:30pm, Sat 7:30am-12pm', 'RTAC Accredited'),
('Melbourne IVF', 'AU', 'Melbourne', 'VIC', -37.8100, 144.9700, ARRAY['IVF', 'ICSI', 'Genetic Testing', 'Fertility Assessment'], '2-3 weeks', true, true, false, false, true, 'Comprehensive fertility services with state-of-the-art laboratory and experienced specialists.', '+61 3 9473 4444', 'https://melbourneivf.com.au', 'Mon-Fri 8am-5pm, Sat 8am-12pm', 'RTAC Accredited'),
('Genea Fertility', 'AU', 'Sydney', 'NSW', -33.8688, 151.2093, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Fertility Health Check', 'Male Fertility'], '1-2 weeks', true, true, false, false, true, 'Award-winning fertility clinic known for high success rates and innovative techniques.', '+61 2 9229 0800', 'https://genea.com.au', 'Mon-Fri 7am-6pm, Sat 7am-1pm', 'RTAC Accredited'),
('IVFAustralia', 'AU', 'Sydney', 'NSW', -33.8750, 151.2100, ARRAY['IVF', 'ICSI', 'Fertility Preservation', 'Donor Program', 'Surrogacy Support'], '2-3 weeks', true, true, false, false, true, 'Part of Virtus Health, offering personalised fertility treatment plans.', '+61 2 9425 8000', 'https://ivf.com.au', 'Mon-Fri 7:30am-5pm', 'RTAC Accredited'),
('Flinders Fertility', 'AU', 'Adelaide', 'SA', -35.0210, 138.5710, ARRAY['IVF', 'ICSI', 'Ovulation Induction', 'Fertility Assessment'], '3-4 weeks', true, false, false, false, true, 'South Australia leading fertility clinic with compassionate and experienced team.', '+61 8 8155 5333', 'https://flindersfertility.com.au', 'Mon-Fri 8am-5pm', 'RTAC Accredited'),
('Queensland Fertility Group', 'AU', 'Brisbane', 'QLD', -27.4705, 153.0260, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Genetic Testing', 'Male Fertility'], '2-3 weeks', true, true, false, false, true, 'Queensland largest fertility group with multiple clinics and advanced embryology labs.', '+61 7 3394 7100', 'https://qfg.com.au', 'Mon-Fri 7am-5pm, Sat 7am-12pm', 'RTAC Accredited'),
('Fertility North', 'AU', 'Perth', 'WA', -31.9505, 115.8605, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Ovulation Tracking'], '3-5 weeks', true, false, false, false, true, 'Specialist fertility care in Western Australia with personalised treatment approaches.', '+61 8 9301 1075', 'https://fertilitynorth.com.au', 'Mon-Fri 8am-4:30pm', 'RTAC Accredited'),
('Canberra Fertility Centre', 'AU', 'Canberra', 'ACT', -35.2809, 149.1300, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Ovulation Induction'], '2-4 weeks', true, false, false, false, true, 'ACT only dedicated fertility clinic offering comprehensive reproductive medicine.', '+61 2 6282 3066', 'https://canberrafertility.com.au', 'Mon-Fri 8:30am-5pm', 'RTAC Accredited'),
('TasIVF', 'AU', 'Hobart', 'TAS', -42.8821, 147.3272, ARRAY['IVF', 'ICSI', 'Fertility Assessment'], '4-6 weeks', true, true, false, false, true, 'Tasmania dedicated fertility service, bringing specialist care closer to home.', '+61 3 6226 1011', 'https://tasivf.com.au', 'Mon-Fri 8am-5pm', 'RTAC Accredited'),
('Adora Fertility', 'AU', 'Melbourne', 'VIC', -37.8200, 144.9500, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Fertility Assessment', 'Affordable IVF'], '1-2 weeks', true, true, false, false, true, 'Affordable fertility treatment options without compromising on quality of care.', '+61 1800 236 722', 'https://adorafertility.com.au', 'Mon-Fri 8am-5pm, Sat 8am-12pm', 'RTAC Accredited'),

-- INDIA (10 clinics)
('Nova IVF Fertility', 'IN', 'Mumbai', 'Maharashtra', 19.0760, 72.8777, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Surrogacy Counselling', 'PGT', 'Donor Program'], '1-2 weeks', false, true, true, true, false, 'India largest chain of fertility centres with international standards and high success rates.', '+91 22 6839 6839', 'https://novaivffertility.com', 'Mon-Sat 9am-6pm', 'NABH Accredited'),
('Cloudnine Fertility', 'IN', 'Bangalore', 'Karnataka', 12.9716, 77.5946, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Hormonal Testing', 'Laparoscopy'], '1 week', false, true, true, true, false, 'Comprehensive fertility and maternity care with world-class infrastructure.', '+91 80 6799 1111', 'https://cloudninecare.com', 'Mon-Sat 8am-8pm', 'NABH Accredited'),
('Indira IVF', 'IN', 'Delhi', 'Delhi', 28.6139, 77.2090, ARRAY['IVF', 'ICSI', 'IUI', 'Egg Freezing', 'Male Infertility', 'Affordable Packages'], '3-5 days', false, true, true, true, false, 'Affordable IVF treatment with presence across 120+ cities in India.', '+91 11 4900 4900', 'https://indiraivf.com', 'Mon-Sat 9am-7pm, Sun 10am-2pm', 'ISO Certified'),
('Bloom IVF', 'IN', 'Mumbai', 'Maharashtra', 19.0890, 72.8700, ARRAY['IVF', 'ICSI', 'Egg Donation', 'Surrogacy Counselling', 'PGT'], '1-2 weeks', false, false, true, true, false, 'Pioneer in assisted reproduction with over two decades of experience.', '+91 22 6143 6143', 'https://bloomivf.com', 'Mon-Sat 9am-6pm', 'NABH Accredited'),
('Milann Fertility', 'IN', 'Bangalore', 'Karnataka', 12.9800, 77.5900, ARRAY['IVF', 'ICSI', 'Fertility Preservation', 'Genetic Counselling'], '1 week', false, true, true, true, false, 'Cutting-edge fertility treatments with compassionate care.', '+91 80 4646 4646', 'https://milann.co.in', 'Mon-Sat 8:30am-6pm', 'NABH Accredited'),
('Apollo Fertility', 'IN', 'Chennai', 'Tamil Nadu', 13.0827, 80.2707, ARRAY['IVF', 'ICSI', 'IUI', 'Egg Freezing', 'Donor Program', 'Hormonal Testing'], '3-5 days', false, true, true, true, false, 'Part of the Apollo hospital network with access to multidisciplinary medical care.', '+91 44 2829 0200', 'https://apollofertility.com', 'Mon-Sat 8am-8pm', 'NABH Accredited'),
('Manipal Fertility', 'IN', 'Bangalore', 'Karnataka', 12.9600, 77.6000, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Laparoscopy', 'Hysteroscopy'], '1-2 weeks', false, true, true, true, false, 'Backed by Manipal Hospitals with integrated fertility and maternity care.', '+91 80 2502 4444', 'https://manipalhospitals.com', 'Mon-Sat 8am-6pm', 'NABH Accredited'),
('Fortis Bloom IVF', 'IN', 'Delhi', 'Delhi', 28.6200, 77.2200, ARRAY['IVF', 'ICSI', 'IUI', 'Male Infertility', 'Surgical Sperm Retrieval'], '3-7 days', false, true, true, true, false, 'Fertility wing of Fortis Healthcare with experienced reproductive specialists.', '+91 11 4277 6222', 'https://fortishealthcare.com', 'Mon-Sat 9am-7pm', 'NABH Accredited'),
('Max Fertility', 'IN', 'Delhi', 'Delhi', 28.6300, 77.2100, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'PGT', 'Donor Program'], '1 week', false, true, true, true, false, 'Premium fertility services within Max Healthcare network.', '+91 11 2651 5050', 'https://maxhealthcare.in', 'Mon-Sat 8am-8pm', 'NABH Accredited'),
('Gaudium IVF', 'IN', 'Delhi', 'Delhi', 28.6100, 77.2000, ARRAY['IVF', 'ICSI', 'Fertility Preservation', 'Third Party Reproduction', 'Recurrent Failure'], '3-5 days', false, true, true, true, false, 'Specialised centre for complex and recurrent fertility cases.', '+91 11 4866 8000', 'https://gaudiumivfcentre.com', 'Mon-Sat 9am-6pm', 'ISO Certified'),

-- PAKISTAN (10 clinics)
('Australian Concept Infertility Medical Centre', 'PK', 'Karachi', 'Sindh', 24.8607, 67.0011, ARRAY['IVF', 'ICSI', 'IUI', 'Egg Freezing', 'Male Infertility'], '1-2 weeks', false, false, true, true, false, 'Pakistan leading fertility centre with Australian-trained specialists.', '+92 21 3530 0361', 'https://australianconcept.com.pk', 'Mon-Sat 9am-7pm', 'ISO Certified'),
('Islamabad IVF Centre', 'PK', 'Islamabad', 'ICT', 33.6844, 73.0479, ARRAY['IVF', 'ICSI', 'IUI', 'Fertility Assessment'], '1-2 weeks', false, false, true, true, false, 'Dedicated fertility clinic in the capital with modern laboratory facilities.', '+92 51 2654 321', 'https://islamabadivf.com', 'Mon-Sat 9am-6pm', 'PMA Registered'),
('Lahore Fertility Care', 'PK', 'Lahore', 'Punjab', 31.5204, 74.3587, ARRAY['IVF', 'ICSI', 'IUI', 'Hormonal Testing', 'Ovulation Induction'], '1 week', false, false, true, true, false, 'Punjab premier fertility clinic offering personalised care.', '+92 42 3578 0000', 'https://lahorefertility.com', 'Mon-Sat 9am-7pm', 'PMA Registered'),
('Aga Khan Fertility Centre', 'PK', 'Karachi', 'Sindh', 24.8900, 67.0700, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Genetic Counselling', 'Hormonal Testing'], '2-3 weeks', false, true, true, true, false, 'Part of the Aga Khan University Hospital with multidisciplinary fertility care.', '+92 21 3493 0051', 'https://aku.edu', 'Mon-Sat 8am-5pm', 'JCI Accredited'),
('LIFE IVF Centre', 'PK', 'Lahore', 'Punjab', 31.5300, 74.3500, ARRAY['IVF', 'ICSI', 'IUI', 'Egg Freezing', 'PGT'], '1-2 weeks', false, false, true, true, false, 'Advanced fertility treatments with experienced embryologists.', '+92 42 3587 1234', 'https://lifeivf.com.pk', 'Mon-Sat 9am-6pm', 'ISO Certified'),
('Concept Fertility Centre', 'PK', 'Rawalpindi', 'Punjab', 33.5651, 73.0169, ARRAY['IVF', 'ICSI', 'IUI', 'Male Infertility'], '1-2 weeks', false, false, true, true, false, 'Affordable fertility treatments in the twin cities region.', '+92 51 5152 000', 'https://conceptfertility.pk', 'Mon-Sat 9am-6pm', 'PMA Registered'),
('Shifa International Fertility', 'PK', 'Islamabad', 'ICT', 33.7000, 73.0500, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Hormonal Testing'], '2-3 weeks', false, true, true, true, false, 'Hospital-based fertility centre with integrated care pathways.', '+92 51 846 1111', 'https://shifa.com.pk', 'Mon-Sat 8am-6pm', 'JCI Accredited'),
('Hameed Latif Fertility Centre', 'PK', 'Lahore', 'Punjab', 31.5100, 74.3600, ARRAY['IVF', 'ICSI', 'IUI', 'Donor Program'], '1 week', false, false, true, true, false, 'Well-established fertility wing within Hameed Latif Hospital.', '+92 42 3586 2281', 'https://hameedlatif.com', 'Mon-Sat 9am-5pm', 'PMA Registered'),
('Rehman Medical IVF', 'PK', 'Peshawar', 'KPK', 34.0150, 71.5249, ARRAY['IVF', 'ICSI', 'IUI', 'Fertility Assessment'], '2-3 weeks', false, false, true, true, false, 'KPK leading fertility centre providing accessible treatment.', '+92 91 5838 000', 'https://rfrmi.com', 'Mon-Sat 9am-5pm', 'PMA Registered'),
('Fauji Foundation Fertility', 'PK', 'Rawalpindi', 'Punjab', 33.5700, 73.0200, ARRAY['IVF', 'ICSI', 'IUI', 'Ovulation Induction'], '2-4 weeks', false, false, true, true, false, 'Subsidised fertility care for military families and civilians.', '+92 51 9270 913', 'https://fauji-foundation.com', 'Mon-Sat 8am-4pm', 'PMA Registered'),

-- MOCK/GENERIC (10 clinics - US/UK for demo)
('New York Fertility Institute', 'US', 'New York', 'NY', 40.7128, -74.0060, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'PGT', 'Donor Program', 'Surrogacy'], '1-2 weeks', false, true, true, true, false, 'Premier fertility centre in Manhattan with cutting-edge reproductive technology.', '+1 212 555 0100', 'https://example-nyfertility.com', 'Mon-Fri 7am-6pm, Sat 8am-1pm', 'SART Member'),
('Bay Area Reproductive Medicine', 'US', 'San Francisco', 'CA', 37.7749, -122.4194, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Fertility Preservation', 'LGBTQ+ Family Building'], '2-3 weeks', false, true, true, true, false, 'Inclusive fertility clinic serving diverse families in the Bay Area.', '+1 415 555 0200', 'https://example-barm.com', 'Mon-Fri 7:30am-5:30pm', 'SART Member'),
('Chicago Reproductive Specialists', 'US', 'Chicago', 'IL', 41.8781, -87.6298, ARRAY['IVF', 'ICSI', 'IUI', 'Male Fertility', 'Genetic Testing'], '1-2 weeks', false, true, true, true, false, 'Midwest leading fertility practice with personalised treatment plans.', '+1 312 555 0300', 'https://example-chicagofert.com', 'Mon-Fri 7am-5pm, Sat 7am-12pm', 'SART Member'),
('Texas Fertility Center', 'US', 'Austin', 'TX', 30.2672, -97.7431, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Donor Program', 'Affordable Options'], '1 week', false, true, true, true, false, 'Compassionate fertility care with transparent pricing.', '+1 512 555 0400', 'https://example-texasfert.com', 'Mon-Fri 7:30am-5pm', 'SART Member'),
('Atlanta Center for Reproductive Medicine', 'US', 'Atlanta', 'GA', 33.7490, -84.3880, ARRAY['IVF', 'ICSI', 'Fertility Assessment', 'Hormonal Testing', 'Surgical Options'], '2-3 weeks', false, true, true, true, false, 'Southeast premier fertility center with comprehensive services.', '+1 404 555 0500', 'https://example-acrm.com', 'Mon-Fri 8am-5pm', 'SART Member'),
('London Fertility Clinic', 'UK', 'London', 'England', 51.5074, -0.1278, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'PGT', 'Donor Program', 'NHS Funded Options'], '3-6 weeks', true, true, false, false, false, 'HFEA-licensed fertility clinic in central London with NHS and private pathways.', '+44 20 7555 0100', 'https://example-londonfert.com', 'Mon-Fri 8am-6pm, Sat 8am-1pm', 'HFEA Licensed'),
('Manchester Fertility', 'UK', 'Manchester', 'England', 53.4808, -2.2426, ARRAY['IVF', 'ICSI', 'Egg Freezing', 'Fertility Assessment', 'Male Fertility'], '4-6 weeks', true, true, false, false, false, 'Award-winning clinic in the North West with transparent success rates.', '+44 161 555 0200', 'https://example-manchfert.com', 'Mon-Fri 8am-5:30pm', 'HFEA Licensed'),
('Edinburgh Fertility Centre', 'UK', 'Edinburgh', 'Scotland', 55.9533, -3.1883, ARRAY['IVF', 'ICSI', 'IUI', 'Fertility Preservation'], '4-8 weeks', true, true, false, false, false, 'Scotland leading fertility centre with both NHS and private treatment.', '+44 131 555 0300', 'https://example-edinfert.com', 'Mon-Fri 8:30am-5pm', 'HFEA Licensed'),
('Birmingham Centre for Reproductive Medicine', 'UK', 'Birmingham', 'England', 52.4862, -1.8904, ARRAY['IVF', 'ICSI', 'Donor Program', 'Surrogacy Support', 'Genetic Testing'], '3-5 weeks', true, true, false, false, false, 'Midlands largest fertility service with hospital-integrated care.', '+44 121 555 0400', 'https://example-birmfert.com', 'Mon-Fri 8am-5pm', 'HFEA Licensed'),
('Cardiff Fertility Institute', 'UK', 'Cardiff', 'Wales', 51.4816, -3.1791, ARRAY['IVF', 'ICSI', 'IUI', 'Fertility Assessment', 'NHS Funded Options'], '6-8 weeks', true, true, false, false, false, 'Wales dedicated fertility service offering accessible treatment options.', '+44 29 555 0500', 'https://example-cardiff-fert.com', 'Mon-Fri 8:30am-4:30pm', 'HFEA Licensed');
